# Generated by Django 5.1.3 on 2024-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('main_flowers', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('on_sale', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='flowers')),
            ],
        ),
    ]
