# Generated by Django 5.1.3 on 2024-11-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterField(
            model_name='flowers',
            name='image',
            field=models.ImageField(upload_to='cat/'),
        ),
    ]
